#######################
#      Site info      #
#######################
title: phamous [ fey-muhs ] # the title of the website
brand: phamous
brand_tag: "[ fey-muhs ]"
name: Thomas Pham
author: Thomas Pham
email: thphamous@gmail.com
description: > # meta data description
  The personal website of Thomas Pham, a software engineer and master's student at UPenn.
footer_text: > # text that will appear at the bottom next to the Copyright statement
  phamous. Made with ❤️ on Jekyll.
keywords: jekyll-theme, jekyll, portfolio, minnie
icon: 🔥 # the favicon, you can be hip and use an emoji
lang: en # language setting, i.e. en for English, fr for French

#######################
#    Site settings    #
#######################
remote_theme: phvmous/minnie
url: https://phvmous.github.io # the hostname of your site, i.e. if Github pages then https://your-username.github.io
github: phvmous # github username
linkedin: phamous # linkedin username
nav_menu: false # enable to have navigation menu links
dark_mode_toggle: true # enable to allow the dark mode toggle button to appear in the nav bar, default is true

plugins:
  - jekyll-seo-tag
  - jekyll-sitemap